export default [
  {
    title: 'Dashboard Alpha',
    key: 'dashboardAlpha',
    url: '/dashboard/alpha',
    icon: 'icmn icmn-stack',
  },
  {
    title: 'Empty Page',
    key: 'empty',
    url: '/empty',
    icon: 'icmn icmn-books',
  },
  {
    title: 'Bán Hàng',
    key: 'sale',
    url: '/sale',
    icon: 'icmn icmn-calculator',
  },
  {
    title: 'Khách Hàng',
    key: 'customer',
    url: '/customer',
    icon: 'icmn icmn-user',
  },
  {
    title: 'Nhà Cung Cấp',
    key: 'supplier',
    url: '/supplier',
    icon: 'icmn icmn-truck',
  },
  {
    title: 'Sản Phẩm',
    key: 'product',
    url: '/product',
    icon: 'icmn icmn-joomla',
  },
  {
    title: 'Thông Báo Hàng Đến',
    key: 'arrival notification',
    url: '/arrival-notification',
    icon: 'icmn icmn-whatsapp',
  },
  {
    title: 'Yêu Cầu Nhập Hàng',
    key: 'import requirement',
    url: '/import-requirement',
    icon: 'icmn icmn-bullhorn',
  },
  {
    title: 'Nhập Xuất Hàng Hóa',
    key: 'export',
    url: '/export',
    icon: 'icmn icmn-loop',
  },
  {
    title: 'Phiếu Kiểm Kho',
    key: 'inventory records',
    url: '/inventory-records',
    icon: 'icmn icmn-clipboard',
  },
  {
    title: 'Nhà Kho',
    key: 'warehouse',
    url: '/warehouse',
    icon: 'icmn icmn-home2',
  },
  {
    title: 'Nhân Sự',
    key: 'employees',
    url: '/employees',
    icon: 'icmn icmn-user-check',
  },
  {
    title: 'Danh Mục',
    key: 'menu',
    url: '/menu',
    icon: 'icmn icmn-list2',
  },
  {
    title: 'Cấu Hình',
    key: 'setting',
    url: '/setting',
    icon: 'icmn icmn-wrench',
  },
]
